name: Pseudo-interactive run on sample data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Pseudo-interactive test
      run: |
        # send input through pipe
        { sleep 1; echo q; sleep 1; echo q; } |./zpool-iostat-viz --from-file about/sample\ zpool_iostat_-wvHp
